// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	service "github.com/jscastelblancoh/users_service/user/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	GetbyIdEndpoint endpoint.Endpoint
	PostEndpoint    endpoint.Endpoint
	DeleteEndpoint  endpoint.Endpoint
	PutEndpoint     endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.UserService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		DeleteEndpoint:  MakeDeleteEndpoint(s),
		GetbyIdEndpoint: MakeGetbyIdEndpoint(s),
		PostEndpoint:    MakePostEndpoint(s),
		PutEndpoint:     MakePutEndpoint(s),
	}
	for _, m := range mdw["GetbyId"] {
		eps.GetbyIdEndpoint = m(eps.GetbyIdEndpoint)
	}
	for _, m := range mdw["Post"] {
		eps.PostEndpoint = m(eps.PostEndpoint)
	}
	for _, m := range mdw["Delete"] {
		eps.DeleteEndpoint = m(eps.DeleteEndpoint)
	}
	for _, m := range mdw["Put"] {
		eps.PutEndpoint = m(eps.PutEndpoint)
	}
	return eps
}
